spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
#    database: MYSQL
#    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: 'update'
      use-new-id-generator-mappings: true
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/dataservice?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    cassandra:
      keyspace-name: ks_person
      contact-points: 192.168.0.10
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
    solr:
      host: http://192.168.0.30:8983/solr

memcached:
  servers: 192.168.0.40


